vim.api.nvim_set_hl(0, "RainbowDelimiterRed",    { fg = "#FF5555" })
vim.api.nvim_set_hl(0, "RainbowDelimiterYellow", { fg = "#F1FA8C" })
vim.api.nvim_set_hl(0, "RainbowDelimiterBlue",   { fg = "#BD93F9" })
vim.api.nvim_set_hl(0, "RainbowDelimiterOrange", { fg = "#FFB86C" })
vim.api.nvim_set_hl(0, "RainbowDelimiterGreen",  { fg = "#50FA7B" })
vim.api.nvim_set_hl(0, "RainbowDelimiterViolet", { fg = "#FF79C6" })
vim.api.nvim_set_hl(0, "RainbowDelimiterCyan",   { fg = "#8BE9FD" })
