#!/bin/bash

SERVICE="openvpn-client@client.service"

if systemctl is-active "$SERVICE" >/dev/null; then
    systemctl stop "$SERVICE"
    notify-send "VPN" "Отключен" -t 2000
else
    systemctl start "$SERVICE"
    notify-send "VPN" "Подключен" -t 2000
fi
