# dsync configuration
[machines]
notebook = { host = "archlinux-notebook-198-212.netbird.cloud", user = "mflkee" }
server-tmn = { host = "mkair-server-tmn.netbird.cloud", user = "mflkee" }
desktop = { host = "archlinux-desktop-12-158.netbird.cloud", user = "mflkee" }
archlinux-server = { host = "archlinux-server.netbird.cloud", user = "mflkee" }
mkair-notebook = { host = "mkair-server.netbird.cloud", user = "mflkee" }

[git]
source = "~/dotfiles"
branch = "main"
remote_url = "https://github.com/mflkee/dotfiles.git"

[hub]
root = "~/projects"

[projects]
dsync = { path = "~/projects/dsync", remote = "git@github.com:mflkee/dsync.git", machines = ["notebook", "desktop", "server-tmn"], branch = "main" }
