#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-0 --mode 1920x1080 --rate 143.85
xsetroot -cursor_name left_ptr
feh --bg-fill --randomize ~/.config/wallpaper/*
# redshift &
xscreensaver -no-splash &
udiskie &
picom --config ~/.config/picom/picom.conf &
dunst &

$HOME/.config/polybar/launch.sh
(sleep 5 && ~/dotfiles/bspwm/scripts/download_manager.sh) &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a obsidian desktop='^9'
bspc rule -a firefox desktop='^1'

bspc config normal_border_color "#282A36"
bspc config active_border_color "#FF79C6"
bspc config focused_border_color "#FFB86C"
bspc config presel_feedback_color "#BD93F9"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config automatic_scheme alternate  # или другой режим (longest_side, spiral)
