#! /bin/sh

# Запуск sxhkd, если ещё не запущен
pgrep -x sxhkd > /dev/null || sxhkd &

# Настройка экрана
xrandr --output DP-0 --mode 1920x1080 --rate 143.85

# Установка курсора
xsetroot -cursor_name left_ptr

# Запуск фонового GIF
#
{{ if eq .chezmoi.hostname "arch-desktop" }}
mpv --loop=inf --no-audio --wid=0x21c /home/mflkee/pictures/berserk.gif &
{{ else if eq .chezmoi.hostname "arch-thinkpad" }}
mpv --loop=inf --no-audio --wid=0x4da /home/mflkee/pictures/berserk.gif &
{{ end }}

# Запуск xscreensaver и других утилит
#xscreensaver -no-splash &
udiskie &
dunst &

# Задержка для стабильности
sleep 2  # Увеличил задержку перед запуском Polybar

# Запуск Polybar
$HOME/.config/polybar/launch.sh &

# Запуск других скриптов
(sleep 5 && ~/.config/bspwm/scripts/download_manager.sh) &

# Настройки bspwm
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle true

# Правила для окон
bspc rule -a obsidian desktop='^9'
bspc rule -a firefox desktop='^1'

# Цвета для окон
bspc config normal_border_color "#282A36"
bspc config active_border_color "#FF79C6"
bspc config focused_border_color "#FFB86C"
bspc config presel_feedback_color "#BD93F9"

# Конфигурация фокуса
bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config automatic_scheme alternate
