color0 #282624
color1 #cf7670
color2 #8ca38a
color3 #bfa67a
color4 #78909c
color5 #b38f99
color6 #7fa39a
color7 #f0ede6
color8 #34312d
color9 #db8b85
color10 #a3b8a1
color11 #d1ba94
color12 #8fa7b3
color13 #c7a3ad
color14 #96b8b0
color15 #fafbfe

cursor                #f0ede6
cursor_text_color     #282624
background            #1e1d1b
foreground            #f0ede6
selection_foreground  #1e1d1b
selection_background  #cabaaa
active_border_color   #cabaaa
inactive_border_color #282624
url_color             #cabaaa

active_tab_foreground   #1e1d1b
active_tab_background   #cabaaa
inactive_tab_foreground #cabaaa
inactive_tab_background #282624
cursor_trail_color      #cabaaa
