# System utilities
alias szsh="source ~/.zshrc"
alias sysoff="sudo shutdown now"
alias du="dust"
alias cat="bat"
alias ls="lsd"
alias ll="lsd -l"
alias l="lsd -l -a"
alias grep="rg"
alias man="tldr"
alias top="gtop"
alias ps="procs"
alias wh="which"
alias clean="~/.config/scripts/archclean.sh"
