format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[\\$](bold fg:#fe8019)"
error_symbol = "[\\$](bold fg:#cc241d)"
vimcmd_symbol = "[\\$](bold fg:#a89984)"

[username]
show_always = false
style_user = "bold fg:#fe8019"
style_root = "bold fg:#cc241d"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "fg:#928374"
format = "[@$hostname]($style) "

[directory]
style = "bold fg:#d5c4a1"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " "
read_only_style = "fg:#cc241d"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold fg:#fe8019"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:#cc241d"
format = "[$all_status$ahead_behind]($style) "
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[cmd_duration]
min_time = 1000
style = "fg:#928374"
format = "[ $duration]($style) "

[time]
disabled = true

[nodejs]
symbol = " "
style = "fg:#d65d0e"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "fg:#d79921"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "fg:#cc241d"
format = "[$symbol$version]($style) "

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true
